apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: productmicroservice:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: product
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root


---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort